from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_criar_conta(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#MainWindow{\n"
"    background-color: rgb(32, 74, 135);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: rgb(32, 74, 135);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(175, 50, 175, 50)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_criar_conta = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_criar_conta.setFont(font)
        self.label_criar_conta.setStyleSheet("#label_criar_conta {\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_criar_conta.setObjectName("label_criar_conta")
        self.verticalLayout.addWidget(self.label_criar_conta, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(-1, 9, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nome.sizePolicy().hasHeightForWidth())
        self.label_nome.setSizePolicy(sizePolicy)
        self.label_nome.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        self.label_nome.setFont(font)
        self.label_nome.setStyleSheet("#label_nome {\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_nome.setObjectName("label_nome")
        self.verticalLayout_3.addWidget(self.label_nome)
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nome.sizePolicy().hasHeightForWidth())
        self.lineEdit_nome.setSizePolicy(sizePolicy)
        self.lineEdit_nome.setMaximumSize(QtCore.QSize(430, 35))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.verticalLayout_3.addWidget(self.lineEdit_nome)
        self.label_cpf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cpf.sizePolicy().hasHeightForWidth())
        self.label_cpf.setSizePolicy(sizePolicy)
        self.label_cpf.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        self.label_cpf.setFont(font)
        self.label_cpf.setStyleSheet("#label_cpf {\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_cpf.setObjectName("label_cpf")
        self.verticalLayout_3.addWidget(self.label_cpf)
        self.lineEdit_cpf = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cpf.sizePolicy().hasHeightForWidth())
        self.lineEdit_cpf.setSizePolicy(sizePolicy)
        self.lineEdit_cpf.setMaximumSize(QtCore.QSize(222, 35))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.lineEdit_cpf.setFont(font)
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.verticalLayout_3.addWidget(self.lineEdit_cpf)
        self.label_data_nascimento = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_nascimento.sizePolicy().hasHeightForWidth())
        self.label_data_nascimento.setSizePolicy(sizePolicy)
        self.label_data_nascimento.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        self.label_data_nascimento.setFont(font)
        self.label_data_nascimento.setStyleSheet("#label_data_nascimento {\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_data_nascimento.setObjectName("label_data_nascimento")
        self.verticalLayout_3.addWidget(self.label_data_nascimento)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMaximumSize(QtCore.QSize(222, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_3.addWidget(self.dateEdit)
        self.label_senha = QtWidgets.QLabel(self.centralwidget)
        self.label_senha.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        self.label_senha.setFont(font)
        self.label_senha.setStyleSheet("#label_senha {\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_senha.setObjectName("label_senha")
        self.verticalLayout_3.addWidget(self.label_senha)
        self.lineEdit_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_senha.sizePolicy().hasHeightForWidth())
        self.lineEdit_senha.setSizePolicy(sizePolicy)
        self.lineEdit_senha.setMaximumSize(QtCore.QSize(222, 35))
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.verticalLayout_3.addWidget(self.lineEdit_senha)
        spacerItem = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_criar_conta = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_criar_conta.sizePolicy().hasHeightForWidth())
        self.pushButton_criar_conta.setSizePolicy(sizePolicy)
        self.pushButton_criar_conta.setMaximumSize(QtCore.QSize(207, 40))
        self.pushButton_criar_conta.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(14)
        self.pushButton_criar_conta.setFont(font)
        self.pushButton_criar_conta.setAutoFillBackground(False)
        self.pushButton_criar_conta.setStyleSheet("#pushButton_criar_conta {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(244, 222, 30);\n"
"    color: rgb(20, 34, 143)\n"
"}")
        self.pushButton_criar_conta.setObjectName("pushButton_criar_conta")
        self.horizontalLayout.addWidget(self.pushButton_criar_conta)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_voltar.sizePolicy().hasHeightForWidth())
        self.pushButton_voltar.setSizePolicy(sizePolicy)
        self.pushButton_voltar.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(14)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setStyleSheet("#pushButton_voltar {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(244, 222, 30);\n"
"    color: rgb(20, 34, 143)\n"
"}")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.horizontalLayout_2.addWidget(self.pushButton_voltar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_criar_conta.setText(_translate("MainWindow", "Criar conta"))
        self.label_nome.setText(_translate("MainWindow", "Nome"))
        self.label_cpf.setText(_translate("MainWindow", "CPF"))
        self.label_data_nascimento.setText(_translate("MainWindow", "Data de nascimento"))
        self.label_senha.setText(_translate("MainWindow", "Senha"))
        self.pushButton_criar_conta.setText(_translate("MainWindow", "Criar conta"))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_criar_conta()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

