from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#MainWindow{\n"
"    background-color: rgb(32, 74, 135);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: rgb(32, 74, 135);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(175, 50, 175, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_faca_o_seu_login = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_faca_o_seu_login.setFont(font)
        self.label_faca_o_seu_login.setStyleSheet("#label_faca_o_seu_login{\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_faca_o_seu_login.setObjectName("label_faca_o_seu_login")
        self.verticalLayout.addWidget(self.label_faca_o_seu_login, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_6.setContentsMargins(93, 0, -1, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem)
        self.label_cpf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cpf.sizePolicy().hasHeightForWidth())
        self.label_cpf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(13)
        self.label_cpf.setFont(font)
        self.label_cpf.setStyleSheet("#label_cpf {\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_cpf.setObjectName("label_cpf")
        self.verticalLayout_6.addWidget(self.label_cpf)
        self.lineEdit_cpf = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cpf.sizePolicy().hasHeightForWidth())
        self.lineEdit_cpf.setSizePolicy(sizePolicy)
        self.lineEdit_cpf.setMaximumSize(QtCore.QSize(250, 40))
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.verticalLayout_6.addWidget(self.lineEdit_cpf)
        self.label_senha = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_senha.sizePolicy().hasHeightForWidth())
        self.label_senha.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(13)
        self.label_senha.setFont(font)
        self.label_senha.setStyleSheet("#label_senha {\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_senha.setObjectName("label_senha")
        self.verticalLayout_6.addWidget(self.label_senha)
        self.lineEdit_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_senha.sizePolicy().hasHeightForWidth())
        self.lineEdit_senha.setSizePolicy(sizePolicy)
        self.lineEdit_senha.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setUnderline(False)
        self.lineEdit_senha.setFont(font)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.verticalLayout_6.addWidget(self.lineEdit_senha)
        spacerItem1 = QtWidgets.QSpacerItem(20, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_6.setStretch(5, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 7, -1, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_entrar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_entrar.sizePolicy().hasHeightForWidth())
        self.pushButton_entrar.setSizePolicy(sizePolicy)
        self.pushButton_entrar.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(14)
        self.pushButton_entrar.setFont(font)
        self.pushButton_entrar.setStyleSheet("#pushButton_entrar {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(244, 222, 30);\n"
"    color: rgb(20, 34, 143)\n"
"}")
        self.pushButton_entrar.setObjectName("pushButton_entrar")
        self.horizontalLayout_2.addWidget(self.pushButton_entrar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_voltar.sizePolicy().hasHeightForWidth())
        self.pushButton_voltar.setSizePolicy(sizePolicy)
        self.pushButton_voltar.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(14)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setStyleSheet("#pushButton_voltar {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(244, 222, 30);\n"
"    color: rgb(20, 34, 143)\n"
"}")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.horizontalLayout.addWidget(self.pushButton_voltar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_faca_o_seu_login.setText(_translate("MainWindow", "Faça o seu login"))
        self.label_cpf.setText(_translate("MainWindow", "CPF"))
        self.label_senha.setText(_translate("MainWindow", "Senha"))
        self.pushButton_entrar.setText(_translate("MainWindow", "     Entrar     "))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

