from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#MainWindow{\n"
"    background-color: rgb(32, 74, 135);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: rgb(32, 74, 135);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(25, 25, 25, 20)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_nome_usuario = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_nome_usuario.setFont(font)
        self.label_nome_usuario.setStyleSheet("#label_nome_usuario{\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_nome_usuario.setObjectName("label_nome_usuario")
        self.horizontalLayout.addWidget(self.label_nome_usuario)
        spacerItem = QtWidgets.QSpacerItem(308, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_atualizar = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_atualizar.sizePolicy().hasHeightForWidth())
        self.pushButton_atualizar.setSizePolicy(sizePolicy)
        self.pushButton_atualizar.setMaximumSize(QtCore.QSize(29, 30))
        self.pushButton_atualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_atualizar.setAutoFillBackground(False)
        self.pushButton_atualizar.setStyleSheet("#pushButton_atualizar { \n"
"    border: none;\n"
"    background-color: #F4DE1E;\n"
"    border-radius: 12px;\n"
"}")
        self.pushButton_atualizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/refresh-svgrepo-com (1).svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.pushButton_atualizar.setIcon(icon)
        self.pushButton_atualizar.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_atualizar.setObjectName("pushButton_atualizar")
        self.horizontalLayout.addWidget(self.pushButton_atualizar)
        self.label_saldo = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(15)
        self.label_saldo.setFont(font)
        self.label_saldo.setStyleSheet("#label_saldo{\n"
"    color: rgb(244, 222, 30);\n"
"}")
        self.label_saldo.setObjectName("label_saldo")
        self.horizontalLayout.addWidget(self.label_saldo, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 800))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalFrame = QtWidgets.QFrame(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_2.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_2.setSizePolicy(sizePolicy)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_3.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_depositar = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_depositar.sizePolicy().hasHeightForWidth())
        self.pushButton_depositar.setSizePolicy(sizePolicy)
        self.pushButton_depositar.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        self.pushButton_depositar.setFont(font)
        self.pushButton_depositar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_depositar.setStyleSheet("#pushButton_depositar {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(244, 222, 30);\n"
"    color: rgb(20, 34, 143)\n"
"}")
        self.pushButton_depositar.setObjectName("pushButton_depositar")
        self.horizontalLayout_3.addWidget(self.pushButton_depositar)
        self.pushButton_sacar = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sacar.sizePolicy().hasHeightForWidth())
        self.pushButton_sacar.setSizePolicy(sizePolicy)
        self.pushButton_sacar.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        self.pushButton_sacar.setFont(font)
        self.pushButton_sacar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_sacar.setStyleSheet("#pushButton_sacar {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(244, 222, 30);\n"
"    color: rgb(20, 34, 143)\n"
"}")
        self.pushButton_sacar.setObjectName("pushButton_sacar")
        self.horizontalLayout_3.addWidget(self.pushButton_sacar)
        self.pushButton_transferir = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_transferir.sizePolicy().hasHeightForWidth())
        self.pushButton_transferir.setSizePolicy(sizePolicy)
        self.pushButton_transferir.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        self.pushButton_transferir.setFont(font)
        self.pushButton_transferir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_transferir.setStyleSheet("#pushButton_transferir {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(244, 222, 30);\n"
"    color: rgb(20, 34, 143)\n"
"}")
        self.pushButton_transferir.setObjectName("pushButton_transferir")
        self.horizontalLayout_3.addWidget(self.pushButton_transferir)
        self.verticalLayout_4.addWidget(self.horizontalFrame_2)
        self.label_historico = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_historico.sizePolicy().hasHeightForWidth())
        self.label_historico.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_historico.setFont(font)
        self.label_historico.setStyleSheet("#label_historico {\n"
"    color: rgb(244, 222, 30)\n"
"}")
        self.label_historico.setObjectName("label_historico")
        self.verticalLayout_4.addWidget(self.label_historico, 0, QtCore.Qt.AlignBottom)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 185))
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(165)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_sair = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sair.sizePolicy().hasHeightForWidth())
        self.pushButton_sair.setSizePolicy(sizePolicy)
        self.pushButton_sair.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        self.pushButton_sair.setFont(font)
        self.pushButton_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_sair.setStyleSheet("#pushButton_sair {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(244, 222, 30);\n"
"    color: rgb(20, 34, 143)\n"
"}")
        self.pushButton_sair.setObjectName("pushButton_sair")
        self.horizontalLayout_4.addWidget(self.pushButton_sair)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.verticalFrame)
        spacerItem3 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_nome_usuario.setText(_translate("MainWindow", "Bem vindo, Vinícius"))
        self.label_saldo.setText(_translate("MainWindow", "Saldo R$ 10.000,00"))
        self.pushButton_depositar.setText(_translate("MainWindow", "Depositar"))
        self.pushButton_sacar.setText(_translate("MainWindow", "Sacar"))
        self.pushButton_transferir.setText(_translate("MainWindow", "Transferir"))
        self.label_historico.setText(_translate("MainWindow", "Histórico de transações"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Data"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Operacao"))
        self.pushButton_sair.setText(_translate("MainWindow", "Sair da Conta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_dashboard()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

